- block:
  - name: "Getting kesl package to temporary folder"
    copy:
      src: "{{ kesl_file_name }}"
      dest: /tmp/{{ kesl_file_name }}
      mode: 0755
      remote_src: false
    tags: kesl

  - name: "Creating answer file for kesl"
    # become: yes
    template:
      src: "kesl.j2"
      dest: "/tmp/kesl.ini"
      mode: 0644
    tags: kesl

  - name: "Installing package"
    become: true
    apt:
      deb: "/tmp/{{ kesl_file_name }}"
      state: present
    tags: kesl

  - name: "Kesl postinstall config"
    become: true
    shell: "{{ default_kesl_bin_path }}/kesl-setup.pl --autoinstall=/tmp/kesl.ini"
    register: postconfig_result    
    notify:  restart kesl

  - name: "Ensure kesl service is enabled"
    become: true
    service:
      name: kesl
      enabled: yes
      state: started
    tags: kesl

  # - name: "Kesl check status"
  #   become: yes
  #   #shell: "{{ default_kesl_bin_path }}/kesl-control -S --app-info"
  #   command: "{{ default_kesl_bin_path }}/kesl-control -S --app-info"
  #   register: cmd_result
  #  # register: Kesl_status
  #   ignore_errors: yes  
  #   notify:  restart kesl

  - name: "Removing temporary files"
    # become: yes
    file: 
      path: "{{ item }}" 
      state: absent
    with_items:
      - "/tmp/{{ kesl_file_name }}"
      - "/tmp/kesl.ini"
  when: metod_kesl == "custom_install"